name: Run rime and validation

on: [push, pull_request]

jobs:
  rime:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.4'
      env:
        ImageOS: ubuntu18

    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install bash libxml2-dev libxslt-dev build-essential binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev cmake curl -y

    - name: Install GCC
      run: sudo apt install gcc g++ -y

    - name: Upgrade pip
      run: python3 -m pip --upgrade pip

    - name: Install Rime
      run: python3 -m pip install git+https://github.com/icpc-jag/rime

    - name: Rime test
      run: rime test -k
