name: Run rime and validation

on: [push, pull_request]

jobs:
  rime:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'
      env:
        ImageOS: ubuntu18

    - name: Install dependencies
      run: apt-get install python3 libpython3.8 python3-dev python3-pip bash libxml2-dev libxslt-dev build-essential binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev cmake curl -y

    - name: Install GCC
      run: apt-get install gcc g++ -y

    - name: Upgrade pip
      run: python3 -m pip --upgrade pip

    - name: Install Rime
      run: python3 -m pip install git+https://github.com/icpc-jag/rime

    - name: Rime test
      run: rime test -k

    - name: Check input file extention
      run: rime test -k
